class MarcaService {
  static final List<String> cities = [
    'ACURA',
    'ALFA ROMEO',
    'ASTON MARTIN',
    'AUDI',
    'Los Angeles',
    'Madrid',
    'Bali',
    'Barcelona',
    'Paris',
    'Bucharest',
    'New York City',
    'Philadelphia',
    'Sydney',
  ];

  static List<String> getSuggestions(String query, List<String> data) {
    List<String> matches = List();
    matches.addAll(data);

    matches.retainWhere((s) => s.toLowerCase().contains(query.toLowerCase()));
    return matches;
  }
}

List<String> marcaLLantas = [
  'Accelera',
  'Aderenza',
  'Aeolus',
  'Amberstone',
  'Antares',
  'Antyre',
  'Atlas',
  'Atturo',
  'Aurora',
  'Autogrip',
  'Barum',
  'BFGoodrich',
  'Blacklion',
  'Bridgestone',
  'Carbon',
  'Carlisle',
  'Continental',
  'Cooper',
  'Daewoo',
  'Dayton',
  'Deestone',
  'Deruibo',
  'Dick Cepek',
  'Dunlop',
  'Duramas',
  'Durun',
  'Euzkadi',
  'Falken',
  'Farroad',
  'Federal',
  'Fesite',
  'Fierce',
  'Firenza',
  'Firestone',
  'Fullrun',
  'Fullway',
  'Fuzion',
  'General',
  'Gladiator',
  'Goalstar',
  'Goodyear',
  'Grandstone',
  'Greatway',
  'GT Radial',
  'Haida',
  'Hankook',
  'Hifly',
  'Inning',
  'Interco',
  'Kapsen',
  'Kelly',
  'Kenda',
  'Keter',
  'Kumho',
  'Kunyuan',
  'Landsail',
  'Landy',
  'Laufenn',
  'Lexani',
  'Lionhart',
  'Mastercraft',
  'Maxtrek',
  'Maxxis',
  'Mazzini',
  'Michelin',
  'Mickey Thompson',
  'Milestar',
  'Mirage',
  'Nankang',
  'Nexen',
  'Nitto',
  'Nokian',
  'Ovation',
  'Pirelli',
  'Pitbull',
  'Primewell',
  'Proload',
  'Racealone',
  'Roadclaw',
  'Roadmaster',
  'Roadshine',
  'Roadstone',
  'Saferich',
  'Sailun',
  'Sailwin',
  'Sava',
  'Seiberling',
  'Starfire',
  'Sumitomo',
  'Sunew',
  'TDI TIRES',
  'Tigar',
  'Torch',
  'Tornel',
  'Torway',
  'Toyo',
  'TracMax',
  'Transking',
  'Transterra',
  'Triangle',
  'Turnpike',
  'Uniroyal',
  'Venezia',
  'Vitour',
  'Wanli',
  'West Lake',
  'Winda',
  'Winrun',
  'Wosen',
  'Yellowsea',
  'Yokohama',
  'Zetum',
];

List<String> listaColores = [
  'Amarillo',
  'Azul',
  'Blanco',
  'Dorado',
  'Gris',
  'Marron',
  'Naranja',
  'Negro',
  'Plata',
  'Purpura',
  'Rojo',
  'Rosa',
  'Verde',
];

List<String> tipoVehiculo = [
  'Sedán',
  'Hatchback',
  'SUV',
  'Deportivos',
  'Van',
  'Pick Up',
  'Camión 3.500 kg',
  'Furgón',
  'Furgoneta',
];

List<String> medidaLLantas = [
  'R13',
  'R14',
  'R15',
  'R16',
  'R17',
  'R18',
  'R20',
  'R22',
];

List<String> listaClientes = [
  "ABA Seguros",
  "Ace Seguros",
  "Autoridad solicitante",
  "AXA Seguros",
  "GNP",
  "HDI",
  "HSBC Seguros",
  "Mapfre",
  "Metlife México",
  "Policia Naval",
  "Qualitas",
  "Seguros Argos",
  "Seguros Banamex",
  "Seguros Banorte",
  "Seguros BBVA",
  "Seguros Inbursa",
  "Transito Coatepec",
  "Transito Coatzacoalcos",
  "Transito Cordoba",
  "Transito Orizaba",
  "Transito Poza Rica",
  "Transito Veracruz",
  "Transito Xalapa",
  "Transporte Publico",
];

Map<String, String> formData = {
  'Tipo': '',
  'Color': '',
  'Autoridad': '',
  'MarcaLlantas': '',
  'MedidaLlantas': '',
  'ModeloAuto': '',
  'MarcaAuto': '',
};
